name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Project Automation+
      uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Backlog
          column: Triage
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
